version: 2
jobs:
  build:
    working_directory: ~/nano-typescript
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.9.0'
      - run:
          name: install dependencies
          command: 'sudo npm install'
      - run:
          name: test
          command: sudo npm run test