version: 2
jobs:
  build:
    working_directory: ~/nano-typescript
    docker:
      - image: circleci/node:latest-browsers
        environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.9.0'
      - run:
          name: permissions
          command: 'chown -R $USER:$USER /home/circleci/nano-typescript/node_modules/'
      - run:
          name: install dependencies
          command: 'sudo npm install'
      - run:
          name: test
          command: sudo npm run test